/* 
Name: Connor Kouznetsov
U-Number:
Description: We can use this program to revisit basic C concepts and syntaxes...

TIP #0: IMPORTANT SYNTAX/UNIX COMMAND REFERENCES
        Link: https://www.geeksforgeeks.org/essential-linuxunix-commands/
        Link: https://dev.to/ifenna__/adding-colors-to-bash-scripts-48g4 // this link is for adding colors to bash scripts...

TIP #1: HOW CAN I USE COMMENTS IN C PROGRAMMING?
    Theres actually 2 ways to use comments in C programming...
        1. If you want to comment out a **Single Line** of code use "//" at the beginning of the statement/comment you make...
        2. If you want to comment out **Multi Line Segments** of code use "/*" at the beginning and the end of the comment/statement...

TIP #2: WHAT IS THE PURPOSE OF "printf(\n);"
    Lets break down what each part of our function means:
        1. "printf" is a function that allows us to print out text to the console...
        2. The "()" are used to indicate that we are using a function...
        3. The "\n" is used to indicate an escape sequence and create a new line in our output...
        4. The ";" is used to indicate the end of ANY statement...

TIP #3: WHAT IS THE PURPOSE OF "return 0;"
    This indicates that our program has successfully executed without any errors...
    If we do not include this statement, our program may not run correctly or may produce unexpected results...   

TIP #4: WHAT IS THE PURPOSE OF "int main()"
    Lets break down each part of this function:
        1. "int" indicates that this function will return an integer value...
        2. "main" is the name of our function...
        3. The use of "()" indicates we're using a function...
        4. The use of "{}" indicates our function(s) start/finish...

TIP #5: WHAT TYPE OF "#include" STATEMENTS ARE THERE FOR C?
    There are 2 types of #include statements:
        1. The first type is the "standard library" which is used to include standard C functions...
        2. The second type is the "user-defined library" which is used to include user-defined functions...
        3. The standard library is included using "#include <stdio.h>"...
        4. The user-defined library is included using "#include "filename.h""...
        5. The standard library is used to include standard C functions such as printf() and scanf()...
        6. The user-defined library is used to include user-defined functions such as myFunction()...         

TIP #6: WHAT IS THE DIFFERENCE BETWEEN "int" AND "double" FOR C PROGRAMMING?
    Lets compare the difference between them?:
        1. "int" stores integer values (whole numbers), making it more efficient & faster by using less memory...
        2. "double" stores floating point values (decimal numbers), making it more precise but slower by using more memory...

TIP #7: WHAT IS HTE 
*/